# Generated by Django 4.2.7 on 2025-09-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0002_tenant_mcptool_required_scopes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.TextField(help_text='Stripe secret key (encrypted)')),
                ('publishable_key', models.CharField(blank=True, help_text='Stripe publishable key', max_length=255)),
                ('webhook_secret', models.TextField(blank=True, help_text='Stripe webhook endpoint secret (encrypted)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_credential', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'Stripe Credential',
                'verbose_name_plural': 'Stripe Credentials',
                'db_table': 'mcp_stripe_credentials',
            },
        ),
        migrations.CreateModel(
            name='MSBookingsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azure_tenant_id', models.CharField(help_text='Azure Active Directory tenant ID', max_length=255)),
                ('client_id', models.CharField(help_text='Azure application client ID', max_length=255)),
                ('client_secret', models.TextField(help_text='Azure application client secret (encrypted)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ms_bookings_credential', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'MS Bookings Credential',
                'verbose_name_plural': 'MS Bookings Credentials',
                'db_table': 'mcp_ms_bookings_credentials',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Google OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='Google OAuth refresh token (encrypted)')),
                ('client_id', models.CharField(help_text='Google OAuth client ID', max_length=255)),
                ('client_secret', models.TextField(help_text='Google OAuth client secret (encrypted)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_credential', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'Google Calendar Credential',
                'verbose_name_plural': 'Google Calendar Credentials',
                'db_table': 'mcp_google_calendar_credentials',
            },
        ),
        migrations.CreateModel(
            name='CalendlyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(help_text='Calendly API token (encrypted)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendly_credential', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'Calendly Credential',
                'verbose_name_plural': 'Calendly Credentials',
                'db_table': 'mcp_calendly_credentials',
            },
        ),
    ]
