# Generated by Django 4.2.7 on 2025-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0003_stripecredential_msbookingscredential_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtoken',
            options={'verbose_name': 'Authentication Token', 'verbose_name_plural': 'Authentication Tokens'},
        ),
        migrations.AlterModelOptions(
            name='mcpsession',
            options={'verbose_name': 'MCP Session', 'verbose_name_plural': 'MCP Sessions'},
        ),
        migrations.AlterModelOptions(
            name='mcptool',
            options={'verbose_name': 'MCP Tool', 'verbose_name_plural': 'MCP Tools'},
        ),
        migrations.AlterModelOptions(
            name='mcptoolcall',
            options={'verbose_name': 'Tool Call Log', 'verbose_name_plural': 'Tool Call Logs'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AddField(
            model_name='msbookingscredential',
            name='business_id',
            field=models.CharField(default='', help_text='Microsoft Bookings business ID or email address', max_length=255),
        ),
        migrations.AddField(
            model_name='msbookingscredential',
            name='staff_ids',
            field=models.JSONField(default=list, help_text='List of default staff member GUIDs for this tenant'),
        ),
    ]
