# Generated by Django 4.2.7 on 2025-09-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0004_alter_authtoken_options_alter_mcpsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbookingscredential',
            name='service_id',
            field=models.CharField(default='', help_text='Default Microsoft Bookings service ID', max_length=255),
        ),
    ]
