# Generated by Django 4.2.7 on 2025-09-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0005_msbookingscredential_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(help_text='Twilio Account SID', max_length=255)),
                ('auth_token', models.TextField(help_text='Twilio Auth Token (encrypted)')),
                ('phone_number', models.CharField(help_text='Twilio phone number (E.164 format, e.g., +15551234567)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_credential', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'Twilio Credential',
                'verbose_name_plural': 'Twilio Credentials',
                'db_table': 'mcp_twilio_credentials',
            },
        ),
    ]
