# Generated by Django 4.2.7 on 2025-09-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0006_twiliocredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource name/title', max_length=255)),
                ('resource_type', models.CharField(choices=[('onedrive', 'OneDrive File'), ('sharepoint', 'SharePoint Document'), ('googledrive', 'Google Drive File'), ('url', 'Web URL'), ('text', 'Text Content')], default='onedrive', max_length=50)),
                ('resource_uri', models.URLField(help_text='OneDrive share link, URL, or resource identifier', max_length=1000)),
                ('description', models.TextField(blank=True, help_text='Description of the resource content')),
                ('tags', models.JSONField(default=list, help_text="Tags for categorizing resources (e.g., ['faq', 'documentation', 'policies'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='mcp.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Resource',
                'verbose_name_plural': 'Tenant Resources',
                'db_table': 'mcp_tenant_resources',
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
