# Generated by Django 4.2.7 on 2025-10-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0007_tenantresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCredential',
        ),
    ]
