# Generated by Django 4.2.7 on 2025-10-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0008_auto_20251002_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Description of this admin token', max_length=255)),
                ('permissions', models.JSONField(default=list, help_text='List of admin permissions')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created this token', max_length=255)),
            ],
            options={
                'verbose_name': 'Admin Token',
                'verbose_name_plural': 'Admin Tokens',
            },
        ),
    ]
