# Generated by Django 4.2.7 on 2025-10-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0009_admintoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintoken',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='msbookingscredential',
            name='azure_tenant_id',
        ),
        migrations.RemoveField(
            model_name='msbookingscredential',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='msbookingscredential',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='admintoken',
            name='scopes',
            field=models.JSONField(default=list, help_text='List of admin scopes'),
        ),
    ]
