# Generated by Django 4.2.7 on 2025-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0010_remove_ms_bookings_azure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_azure_tenant_id',
            field=models.CharField(blank=True, help_text='Azure Active Directory tenant ID for MS Bookings', max_length=255),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_business_id',
            field=models.CharField(blank=True, help_text='Microsoft Bookings business ID or email address', max_length=255),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_client_id',
            field=models.CharField(blank=True, help_text='Azure application client ID for MS Bookings', max_length=255),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_client_secret',
            field=models.TextField(blank=True, help_text='Azure application client secret for MS Bookings (encrypted)'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_service_id',
            field=models.CharField(blank=True, help_text='Default Microsoft Bookings service ID', max_length=255),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ms_bookings_staff_ids',
            field=models.JSONField(default=list, help_text='List of default staff member GUIDs for MS Bookings'),
        ),
    ]
