# Generated by Django 4.2.7 on 2025-10-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0011_add_ms_bookings_to_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_azure_tenant_id',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_client_id',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_client_secret',
        ),
    ]
