# Generated by Django 4.2.7 on 2025-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0012_remove_azure_fields_from_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSBookingsCredential',
        ),
    ]
