# Generated by Django 4.2.7 on 2025-10-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0013_remove_msbookingscredential_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_business_id',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_service_id',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='ms_bookings_staff_ids',
        ),
        migrations.CreateModel(
            name='MSBookingsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='', help_text='Microsoft Bookings business ID or email address', max_length=255)),
                ('staff_ids', models.JSONField(default=list, help_text='List of default staff member GUIDs for this token')),
                ('service_id', models.CharField(default='', help_text='Default Microsoft Bookings service ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ms_bookings_credential', to='mcp.authtoken')),
            ],
            options={
                'verbose_name': 'MS Bookings Credential',
                'verbose_name_plural': 'MS Bookings Credentials',
                'db_table': 'mcp_ms_bookings_credentials',
            },
        ),
    ]
