# Generated by Django 4.2.7 on 2025-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0014_add_msbookingscredential_with_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbookingscredential',
            name='azure_tenant_id',
            field=models.CharField(default='', help_text='Azure AD tenant ID for this token', max_length=255),
        ),
    ]
